# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}  # matrix of versions 
        # dotnet-version: 6.0.x                       # specifiv version
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  deploy-test:
    runs-on: ubuntu-latest
    needs: build
    environment: Testowanie         # wskazanie naszego Environments
    concurrency: Testowanie
    steps:
      - run: echo Deploying on test server
      - run: echo ${{ secrets.secret1 }}
  
